name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu_build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@protoc
      - run: cargo build

  fmt:
    name: Format check on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run fmt
        run: cargo fmt --all --check

  clippy:
    name: Clippy Check on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run clippy
        run: cargo clippy
